import {} from '../../../pages/admin/team/components/members-list/MembersList';
import { Member } from '../../../types/TeamPage';

export const mockMembers: Member[] = [
    {
        id: 1,
        fullName: 'John Brown',
        img: null,
        description: 'Software Engineer',
        status: 'Опубліковано',
        category: 'Наглядова рада',
    },
    {
        id: 2,
        img: null,
        fullName: 'John Jones',
        description: 'HR Specialist',
        status: 'Опубліковано',
        category: 'Основна команда',
    },
    {
        id: 3,
        img: null,
        fullName: 'Emma Anderson',
        description: 'DevOps Engineer',
        status: 'Опубліковано',
        category: 'Радники',
    },
    {
        id: 4,
        img: null,
        fullName: 'Daniel Miller',
        description: 'HR Specialist',
        status: 'Опубліковано',
        category: 'Радники',
    },
    {
        id: 5,
        img: null,
        fullName: 'John Williams',
        description: 'Software Engineer',
        status: 'Чернетка',
        category: 'Радники',
    },
    {
        id: 6,
        img: null,
        fullName: 'Mia Garcia',
        description: 'Marketing Manager',
        status: 'Чернетка',
        category: 'Наглядова рада',
    },
    {
        id: 7,
        img: null,
        fullName: 'Mia Brown',
        description: 'Marketing Manager',
        status: 'Опубліковано',
        category: 'Наглядова рада',
    },
    {
        id: 8,
        img: null,
        fullName: 'Michael Williams',
        description: 'DevOps Engineer',
        status: 'Опубліковано',
        category: 'Основна команда',
    },
    {
        id: 9,
        img: null,
        fullName: 'Olivia Davis',
        description: 'Frontend Developer',
        status: 'Опубліковано',
        category: 'Наглядова рада',
    },
    {
        id: 10,
        img: null,
        fullName: 'John Brown',
        description: 'QA Analyst',
        status: 'Чернетка',
        category: 'Радники',
    },
    {
        id: 11,
        img: null,
        fullName: 'Olivia Garcia',
        description: 'DevOps Engineer',
        status: 'Чернетка',
        category: 'Основна команда',
    },
    {
        id: 12,
        img: null,
        fullName: 'Daniel Smith',
        description: 'Business Analyst',
        status: 'Опубліковано',
        category: 'Наглядова рада',
    },
    {
        id: 13,
        img: null,
        fullName: 'David Jones',
        description: 'Marketing Manager',
        status: 'Чернетка',
        category: 'Основна команда',
    },
    {
        id: 14,
        img: null,
        fullName: 'David Miller',
        description: 'DevOps Engineer',
        status: 'Опубліковано',
        category: 'Радники',
    },
    {
        id: 15,
        img: null,
        fullName: 'Olivia Garcia',
        description: 'Backend Developer',
        status: 'Опубліковано',
        category: 'Основна команда',
    },
    {
        id: 16,
        img: null,
        fullName: 'David Garcia',
        description: 'Marketing Manager',
        status: 'Чернетка',
        category: 'Радники',
    },
    {
        id: 17,
        img: null,
        fullName: 'Mia Garcia',
        description: 'HR Specialist',
        status: 'Чернетка',
        category: 'Радники',
    },
    {
        id: 18,
        img: null,
        fullName: 'Michael Johnson',
        description: 'Frontend Developer',
        status: 'Опубліковано',
        category: 'Радники',
    },
    {
        id: 19,
        img: null,
        fullName: 'Mia Johnson',
        description: 'Project Manager',
        status: 'Чернетка',
        category: 'Радники',
    },
    {
        id: 20,
        img: null,
        fullName: 'Mia Smith',
        description: 'DevOps Engineer',
        status: 'Чернетка',
        category: 'Основна команда',
    },
    {
        id: 21,
        img: null,
        fullName: 'James Williams',
        description: 'Frontend Developer',
        status: 'Опубліковано',
        category: 'Наглядова рада',
    },
    {
        id: 22,
        img: null,
        fullName: 'David Garcia',
        description: 'Frontend Developer',
        status: 'Чернетка',
        category: 'Наглядова рада',
    },
    {
        id: 23,
        img: null,
        fullName: 'James Davis',
        description: 'QA Analyst',
        status: 'Опубліковано',
        category: 'Наглядова рада',
    },
    {
        id: 24,
        img: null,
        fullName: 'Daniel Miller',
        description: 'Backend Developer',
        status: 'Чернетка',
        category: 'Радники',
    },
    {
        id: 25,
        img: null,
        fullName: 'Daniel Smith',
        description: 'Marketing Manager',
        status: 'Опубліковано',
        category: 'Радники',
    },
    {
        id: 26,
        img: null,
        fullName: 'Daniel Brown',
        description: 'DevOps Engineer',
        status: 'Чернетка',
        category: 'Радники',
    },
    {
        id: 27,
        img: null,
        fullName: 'John Jones',
        description: 'Business Analyst',
        status: 'Опубліковано',
        category: 'Наглядова рада',
    },
    {
        id: 28,
        img: null,
        fullName: 'John Smith',
        description: 'UI/UX Designer',
        status: 'Опубліковано',
        category: 'Наглядова рада',
    },
    {
        id: 29,
        img: null,
        fullName: 'Emma Williams',
        description: 'DevOps Engineer',
        status: 'Опубліковано',
        category: 'Наглядова рада',
    },
    {
        id: 30,
        img: null,
        fullName: 'Michael Miller',
        description: 'Software Engineer',
        status: 'Опубліковано',
        category: 'Основна команда',
    },
    {
        id: 31,
        img: null,
        fullName: 'Ava Johnson',
        description: 'Backend Developer',
        status: 'Чернетка',
        category: 'Радники',
    },
    {
        id: 32,
        img: null,
        fullName: 'Olivia Anderson',
        description: 'Project Manager',
        status: 'Чернетка',
        category: 'Основна команда',
    },
    {
        id: 33,
        img: null,
        fullName: 'David Johnson',
        description: 'Marketing Manager',
        status: 'Чернетка',
        category: 'Радники',
    },
    {
        id: 34,
        img: null,
        fullName: 'Daniel Brown',
        description: 'UI/UX Designer',
        status: 'Чернетка',
        category: 'Радники',
    },
    {
        id: 35,
        img: null,
        fullName: 'David Johnson',
        description: 'Marketing Manager',
        status: 'Опубліковано',
        category: 'Наглядова рада',
    },
    {
        id: 36,
        img: null,
        fullName: 'Ava Anderson',
        description: 'Marketing Manager',
        status: 'Чернетка',
        category: 'Основна команда',
    },
    {
        id: 37,
        img: null,
        fullName: 'John Brown',
        description: 'Project Manager',
        status: 'Опубліковано',
        category: 'Наглядова рада',
    },
    {
        id: 38,
        img: null,
        fullName: 'James Davis',
        description: 'Project Manager',
        status: 'Опубліковано',
        category: 'Основна команда',
    },
    {
        id: 39,
        img: null,
        fullName: 'Emma Smith',
        description: 'UI/UX Designer',
        status: 'Чернетка',
        category: 'Наглядова рада',
    },
    {
        id: 40,
        img: null,
        fullName: 'Mia Brown',
        description: 'Software Engineer',
        status: 'Опубліковано',
        category: 'Основна команда',
    },
    {
        id: 41,
        img: null,
        fullName: 'Olivia Williams',
        description: 'Backend Developer',
        status: 'Опубліковано',
        category: 'Радники',
    },
    {
        id: 42,
        img: null,
        fullName: 'David Jones',
        description: 'DevOps Engineer',
        status: 'Опубліковано',
        category: 'Основна команда',
    },
    {
        id: 43,
        img: null,
        fullName: 'Mia Wilson',
        description: 'QA Analyst',
        status: 'Чернетка',
        category: 'Наглядова рада',
    },
    {
        id: 44,
        img: null,
        fullName: 'Mia Brown',
        description: 'Marketing Manager',
        status: 'Опубліковано',
        category: 'Наглядова рада',
    },
    {
        id: 45,
        img: null,
        fullName: 'Michael Brown',
        description: 'UI/UX Designer',
        status: 'Опубліковано',
        category: 'Наглядова рада',
    },
    {
        id: 46,
        img: null,
        fullName: 'James Davis',
        description: 'HR Specialist',
        status: 'Чернетка',
        category: 'Основна команда',
    },
    {
        id: 47,
        img: null,
        fullName: 'James Brown',
        description: 'Marketing Manager',
        status: 'Чернетка',
        category: 'Радники',
    },
    {
        id: 48,
        img: null,
        fullName: 'Olivia Brown',
        description: 'HR Specialist',
        status: 'Опубліковано',
        category: 'Радники',
    },
    {
        id: 49,
        img: null,
        fullName: 'Olivia Miller',
        description: 'DevOps Engineer',
        status: 'Чернетка',
        category: 'Радники',
    },
    {
        id: 50,
        img: null,
        fullName: 'James Jones',
        description: 'Business Analyst',
        status: 'Опубліковано',
        category: 'Основна команда',
    },
    {
        id: 51,
        img: null,
        fullName: 'John Jones',
        description: 'DevOps Engineer',
        status: 'Чернетка',
        category: 'Основна команда',
    },
    {
        id: 52,
        img: null,
        fullName: 'Mia Williams',
        description: 'DevOps Engineer',
        status: 'Чернетка',
        category: 'Основна команда',
    },
    {
        id: 53,
        img: null,
        fullName: 'John Anderson',
        description: 'Software Engineer',
        status: 'Опубліковано',
        category: 'Основна команда',
    },
    {
        id: 54,
        img: null,
        fullName: 'James Miller',
        description: 'Backend Developer',
        status: 'Чернетка',
        category: 'Наглядова рада',
    },
    {
        id: 55,
        img: null,
        fullName: 'Emma Wilson',
        description: 'DevOps Engineer',
        status: 'Чернетка',
        category: 'Радники',
    },
];
