name: Main pipline Frontend

on:
  push:
    branches:
      - 'release/**'
env:
  RUN_NUM: ${{ github.run_number }}
  
jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Run unit tests
        run: npm run test:cover  

  docker:
    name: Build and push docker image
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
     - name: Check out the repo
       uses: actions/checkout@v4
     - name: "Run docker build and doker push"
       run:  echo "Tag for image ${GITHUB_REF##*/}.${RUN_NUM}"    
     - name: Log in to Docker Hub
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
     - name: Extract metadata for Docker
       id: meta
       uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
       with:
          images: |
            victorycenterua/client     
     - name: Build and push Docker images
       id: push
       uses: docker/build-push-action@v6
       with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}.${{ github.run_number }}
          labels: ${{ steps.meta.outputs.labels }}
          secret-envs: |
            REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }}
